filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
        - 'src/templates/*'
        
before_commands:
    - composer install
        
tools:
    php_cpd: true
    php_pdepend: true
    php_code_coverage: true
